# Generated by Django 3.1.14 on 2024-10-19 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0014_auto_20241019_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='evolution',
            new_name='previous_evolution',
        ),
    ]
